# Generated by Django 4.2 on 2024-02-24 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Countrymas',
            fields=[
                ('countryid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'countrymas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Shareamountdetails',
            fields=[
                ('shareamountref', models.AutoField(primary_key=True, serialize=False)),
                ('duration', models.SmallIntegerField(blank=True, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('paymentmode', models.CharField(blank=True, max_length=20, null=True)),
                ('startdate', models.DateField(blank=True, null=True)),
                ('officestaff', models.CharField(blank=True, max_length=150, null=True)),
            ],
            options={
                'db_table': 'shareamountdetails',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Shareamountinstallments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shareamountref', models.IntegerField(blank=True, null=True)),
                ('slno', models.IntegerField(blank=True, null=True)),
                ('dueamount', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('duedate', models.DateField(blank=True, null=True)),
                ('paidamount', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('status', models.CharField(blank=True, max_length=1, null=True)),
            ],
            options={
                'db_table': 'shareamountinstallments',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Shareholders',
            fields=[
                ('shareholderid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=150, null=True)),
                ('mobile', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'shareholders',
                'managed': False,
            },
        ),
    ]
